### ISSUE TITLE
Failed to load (& save) chunks (1.21.4 fabric). 

### ISSUE THREAD

**Issue by Tyranoraptor** [Ladysnake/Cardinal-Components-API#193] opened 2024-12-04 13:38 UTC
So i use a bunch of mods to optimize my game and played on my singleplayer world for a while to find out that items stored in chest disappear after logging out and logging back in. I removed a few mods in a separate folder to try which one was causing the issue. The Cardinal componenets API version 6.2.0 for minecraft java fabric 1.21.4 is the problem and it doesn't save the world for some reason. Also listing all the mods I am using :-

-cloth config (This one was for version 1.21.3 but works fine with 1.21.4 according to the game. So this might be the issue idk)
-entity model features
-entity texture features
-essential fabric
-fabric api (ofcourse)
-gamma utils
-iris
-Ksyxis
-lamb dynamic lights
-lithium
-mod menu
-reeses sodium options
-sodium extra
-sodium
-speedrun IGT

**Comment by Psora1** [comment] 2024-12-04 18:48
Having this same issue too. For some reason installing the latest build of C2ME semi-fixes the problem, but instead of causing chunk error messages it causes insane console spam from C2ME instead. Pick your poison type thing... I've removed both mods from my mod folder until both are fully updated to 1.21.4, cause this is a bit ridiculous lol.

**Comment by Pyrofab** [comment] 2024-12-04 22:24
Could you post a game log after this issue happens ?

**Comment by dicedpixels** [comment] 2024-12-07 15:42
@Pyrofab I believe I reported the same while back: https://github.com/Ladysnake/Cardinal-Components-API/issues/188. Logs included.

**Comment by Pyrofab** [comment] 2024-12-27 13:14
Duplicate of #188

**Closed as not planned by Pyrofab** 2024-12-27 13:14 UTC
Labels: bug, components-chunk
