### ISSUE TITLE
Crash on loading singleplayer world

### ISSUE THREAD

**Issue by sorat0mo** [Ladysnake/Cardinal-Components-API#114] opened 2022-01-27 05:45 UTC
The log:

---- Minecraft Crash Report ----
// Oops.

Time: 27/1/2022, 1:44 pm
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentContainer net.minecraft.class_5268.getComponentContainer()'
	at net.minecraft.server.MinecraftServer.handler$beo000$onEndTick(MinecraftServer.java:3260)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:861)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ElvenLilith** [comment] 2022-01-28 02:47
I'm also getting the same issue, on 1.18.1. cardinal components and fabric api are the only mods I have installed. crashed as soon as the world was about to load, every time I tried.

Time: 1/27/22, 9:42 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentContainer net.minecraft.class_5268.getComponentContainer()'
	at net.minecraft.server.MinecraftServer.handler$zbh000$onEndTick(MinecraftServer.java:1760)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:861)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by thebestSham** [comment] 2022-01-29 09:01
I'm also getting this bug, I have to assume the error means the change on 4.1.0 is causing this  "Changed the maven group from io.github.onyxstudios.Cardinal-Components-API to dev.onyxstudios.cardinal-components-api" when I revert to 4.0.1 the game runs as intended. https://github.com/MrMelon54/Cardinal-Components-API/releases/tag/4.0.1

Time: 29/01/22, 9:26 pm
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentContainer net.minecraft.class_5268.getComponentContainer()'
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65)
	at net.minecraft.server.MinecraftServer.handler$znm000$onEndTick(MinecraftServer:1760)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:861)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:99)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)

**Comment by cannon9009** [comment] 2022-01-29 17:28
Same issue here. [Here's my report on Crashy.](https://crashy.net/Dk8AopLhRGGyFOxeScnI)

**Comment by Pyrofab** [comment] 2022-02-20 13:02
Sorry about that, should be fixed now.

**Closed as completed by Pyrofab** 2022-02-20 13:02 UTC
