### ISSUE TITLE
whenever i join a server the whole game crashes and this mod is the issue

### ISSUE THREAD

**Issue by ImBigManBurger69** [Ladysnake/Cardinal-Components-API#137] opened 2022-08-27 19:22 UTC
how do i fix it, i cant delete cause its a depency for another mod pls help

**Comment by Pyrofab** [comment] 2022-08-27 21:39
Can you please share the crash report ?

**Comment by Pyrofab** [comment] 2022-09-13 16:28
Assuming duplicate of #138 or #139

**Closed as not planned by Pyrofab** 2022-09-13 16:28 UTC
