### ISSUE TITLE
Creative inventory

### ISSUE THREAD

**Issue by frederic-orlando** [Ladysnake/Cardinal-Components-API#56] opened 2020-09-28 02:58 UTC
Any vanilla items and blocks are missing from creative inventory

I have tried :
1. clean install (no mods) + cardinal, working fine
2. modded + cardinal, missing items and blocks
3. modded without cardinal, working fine

Here is my mod list (from console)
https://pastebin.com/1iBhgzfC

In-game screenshot
![image](https://user-images.githubusercontent.com/50309351/94385295-fac24c80-016e-11eb-8e86-562ec12f6079.png)

**Comment by UpcraftLP** [comment] 2020-09-30 11:43
I've looked into this issue, and wasn't able to reproduce it yet.
It seems to be some mod-specific issue.

**Comment by Pyrofab** [comment] 2020-09-30 14:10
Can't seem to reproduce, is there any chance you can find exactly with which mod(s) it starts breaking ?

**Comment by TheBrokenRail** [comment] 2020-10-21 16:18
This happens when you load ``Item`` early which loads ``ItemGroup``. When ``ItemGroup`` loads, it loads ``Item``, CC makes ``Item`` load ``Items``. ``Items`` tries to initialize all the builtin items, but it can't load any Item groups because those are being loaded as a parent. I am skipping a few steps here because I last debugged this a while ago, but the fix is just to make sure you don't load ``Item`` until it is ready. How I fixed it: https://gitea.thebrokenrail.com/TheBrokenRail/EnergonRelics/commit/fbb1020ce8bcb35e277d593cadf9452319a1ce7f

**Comment by Pyrofab** [comment] 2020-10-21 22:35
If `cardinal-components-item`'s eager loading is the issue, I have good news: it should be fixed in the latest version. Could you confirm maybe ?

**Comment by Pyrofab** [comment] 2020-11-08 17:56
Assuming this issue is resolved, please reopen it if it still occurs.

**Closed as completed by Pyrofab** 2020-11-08 17:56 UTC
Labels: bug, help wanted, mod compat, components-item
